example/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listings.urls')),
    path('users/', include('users.urls')),
]

# Serve media files locally in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from .import views

app_name = 'listings'

urlpatterns = [
    path('', views.index, name='index'),   
    path('greetings/', views.greetings, name='greetings'),
    path('all_listings/', views.all_listings, name='all_listings'),
    path('new_listing/', views.new_listing, name='new_listing'),
    path('all_listings/<detail_id>/', views.detail, name='detail'), 
    path('my_listings/', views.my_listings, name='my_listings'),
    path('edit_listing/<edit_id>/', views.edit_listing, name='edit_listing'),
    path('delete_listing/<delete_id>/', views.delete_listing, name='delete_listing')
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('log_out/', views.log_out, name='log_out'),
    path('register/', views.register, name='register'),
]

listings/models.py
from django.db import models
from django.utils.timezone import now
from datetime import datetime
from django.contrib.auth.models import User


class Listings(models.Model):

    class SaleType(models.TextChoices):
        PICK_UP = "Available for pickup"
        SHIP = "Available for shipping"

    class ConditionType(models.TextChoices):
        USED = "Used"
        NEW = "New"

    class ProductType(models.TextChoices):
        BIKE = "Bike"
        PARTS = "Parts"
        MODELS = "Models"
        OTHER = "Other"

  
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    condition = models.CharField(
        max_length=50, choices=ConditionType.choices, default=ConditionType.USED)
    product_type = models.CharField(
        max_length=50, choices=ProductType.choices, default=ProductType.BIKE)
    sale_type = models.CharField(
        max_length=50, choices=SaleType.choices, default=SaleType.SHIP)
    price = models.FloatField()
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=25)
    state = models.CharField(max_length=25)
    zipcode = models.CharField(max_length=25)
    main_photo = models.ImageField()
    photo_1 = models.ImageField()
    photo_2 = models.ImageField(blank=True)
    list_date = models.DateTimeField(default=now)
    contact_email = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Listings"

users/models.py
from django.db import models

# Create your models here.

listings/forms.py
from django import forms
from .models import Listings

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listings
        fields = ['title', 'condition', 'product_type', 'sale_type', 'price', 'main_photo', 'photo_1',
                  'photo_2', 'city', 'state', 'zipcode', 'contact_email', 'list_date']

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

listings/views.py
from django.shortcuts import render, redirect
from .models import Listings
from .forms import ListingForm
from .filters import ListingFilter
# Create your views here.

def index(request):
    return render(request, 'listings/index.html')

def greetings(request):
    return render(request, 'listings/greetings.html')

def all_listings(request):
    all_listings = Listings.objects.order_by('-list_date')
    my_Filter = ListingFilter(request.GET, queryset=all_listings)
    all_listings = my_Filter.qs
    context = {'all_listings': all_listings, 'my_Filter': my_Filter}
    return render(request, 'listings/all_listings.html', context)

def new_listing(request):
    if request.method != 'POST':
        form = ListingForm()
    else:
        form = ListingForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect('listings:all_listings')
      
    context = {'form': form}
    return render(request, 'listings/new_listing.html', context)

def detail(request, detail_id):
    detail = Listings.objects.get(id=detail_id)
    context = {'detail': detail}
    return render(request, 'listings/detail.html', context)

def my_listings(request):
    my_listings = Listings.objects.order_by('-list_date')
    context = {'my_listings': my_listings}
    return render(request, 'listings/my_listings.html', context)

def edit_listing(request, edit_id):
    listing = Listings.objects.get(id=edit_id)
    if request.method != 'POST':
        form = ListingForm(instance=listing)
    else:
        form = ListingForm(instance=listing, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('listings:all_listings')
    context = {'listing': listing, 'form': form}
    return render(request, 'listings/edit_listing.html', context)

def delete_listing(request, delete_id):
    listing = Listings.objects.get(id=delete_id)
    if request.method == 'POST':
        listing.delete()
        return redirect('listings:my_listings')
    context = {'listing': listing}
    return render(request, 'listings/delete_listing.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .forms import UserForm
from django.contrib.auth import logout

# Create your views here.

def log_out(request):
    logout(request)
    return redirect('listings:index')

def register(request):
    if request.method != 'POST':
        form = UserForm()
    else:
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

listings/templates/listings/all_listings.html
{% extends "listings/base.html" %}
{% load crispy_forms_tags %}

{%block content%} 

<div class="container text-center p-3 " style="width:500px;">
    <h1 class="text-dark">Listings</h1>
    <div class="form-group">
        <div class="card card-body bg-light text-dark rounded" style="width:100%;">
            <form method="get">
                <div class="row ">
                    <div class="col-md-3">
                        {{ my_Filter.form.condition|as_crispy_field }}
                    </div>
                    <div class="col-md-3">
                        {{ my_Filter.form.state|as_crispy_field }}
                    </div>
                    <div class="col-md-3">
                        {{ my_Filter.form.city|as_crispy_field }}
                    </div>
                    <div class="col-md-3 p-2">
                        <button class="btn btn-warning border-dark mt-4" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div> 
                   
<div class="container">
    <div class="card card-body bg-light text-dark text-center p-3 ">
        {% for listing in all_listings %}
        <p><img class="card-img-right img-thumbnail"  src="{{ listing.main_photo.url }}" width=300px height=200px style="max-height:200px" alt="connect">
        <img class="card-img-right img-thumbnail" src="{{ listing.photo_1.url }}" width=300px height=200px style="max-height:200px" alt="connect"></p>
        <p><b>Title:</b> {{ listing.title }}</p>
        <p><b>Condition:</b> {{ listing.condition }}</p>
        <p><b>Sale Type:</b> {{ listing.sale_type }}</p>
        <p><b>Price:</b> $ {{ listing.price|floatformat:2 }}</p>
        <p><b>Location:</b> {{ listing.city }}, {{ listing.state }}</p>
        <p><b>Post Date:</b> {{ listing.list_date }}</p>
        <ul><a class="btn btn-warning border-dark" href="{% url 'listings:detail' listing.id %}">View Listing</a></ul>
        <hr>                 
        {% endfor %}                  
    </div>
</div>
            
{%endblock content%} 

listings/templates/listings/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet">
        
        <title>BikeFinder</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'listings:index' %}"><h3 class="text-warning">BikeFinder</h3></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'listings:all_listings' %}">Listings</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'listings:my_listings' %}">My Listings</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:register' %}">Register</a> 
                            </li>
                        {% endif %}
                    </ul>
                </div>
                {% if user.is_authenticated %}
                    <p class="text-white mt-3 px-4">{{ user.username }}</p>
                    <button class="btn btn-sm btn-warning" type="submit"> <a class="nav-link text-dark" href="{% url 'users:logout' %}"><strong>Logout</strong></a></button>
                {% else %}
                    <button class="btn btn-sm btn-warning" type="submit"> <a class="nav-link text-dark" href="{% url 'users:login' %}"><strong>Login</strong></a></button>
                {% endif %}
            </div>
        </nav>

        <!-- Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      
    </body>
</html>               
      
{%block content%}
      
{%endblock content%}  

listings/templates/listings/delete_listing.html
{% extends "listings/base.html" %}

{% block content %}
<div class="main">     
    <form method="POST"> 
        <div class="container">
            <!-- Security token by Django -->
            {% csrf_token %} 
            <h3>Do you want to delete <b>{{listing.title}}</b> listing ? </h3>
            <p><input type="submit" class="btn" value="Delete" /> 
            <a class= "btn" href="{% url 'listings:my_listings'%}">Cancel</a></p>
        </div>
    </form> 
</div> 

{% endblock content %}

listings/templates/listings/detail.html
{% extends "listings/base.html" %}

{%block content%} 
<div class="container">
    <div class="row p-5">
        <div class="col">
            <h3 class="text-dark mb-4">LISTING:</h3>
            <p><b>Title:</b> {{ detail.title }}</p>
            <p><b>Condition:</b> {{ detail.condition }}</p>
            <p><b>Product Type:</b> {{ detail.product_type }}</p>
            <p><b>Sale Type:</b> {{ detail.sale_type }}</p>
            <p><b>Price: $</b> {{ detail.price }}</p>
            <p><b>Location:</b> {{ detail.city }}, {{ detail.state }}</p>
            <p><b>Contact Email:</b> {{ detail.contact_email }}</p>
            <p><b>Post Date:</b> {{ detail.list_date }}</p>
        </div>
        <div class="col-4 mt-4">
            <img class = "card mb-3 " src="{{ detail.main_photo.url }}" width= 350px height=300px style= "max-width: 100%; max-height: 100%;" />
            {% if detail.photo_2%}
            <img class = "card " src="{{ detail.photo_2.url }}" width= 350px height=300px style= "max-width: 100%; max-height: 100%;"/>
            {% endif %}
        </div>
        <div class="col-4 mt-4">
            <img class = "card " src="{{ detail.photo_1.url }}" width= 350px height=300px style= "max-width: 100%; max-height: 100%;" />
        </div>
    </div>
</div>
              
{%endblock content%}

listings/templates/listings/edit_listing.html
{% extends "listings/base.html" %}

{% block content %}

<h1>EDITING</h1>

<form action="{% url 'listings:edit_listing' listing.id %}" method='post' enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
        {{ form.as_p }}
    </div>
    <button type="submit" class="btn">Edit listing</button>
</form>

{% endblock content %}  

listings/templates/listings/greetings.html
<h1>GREETINGS</h1>

<h4>Welcome to my site!</h4>

listings/templates/listings/homepage.html
{% extends "listings/base.html" %}

{%block content%}

<main>
  <div class="container py-4">
   
    <div class="p-5 mb-4 bg-warning rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">BIKE FINDER</h1>
            <p class="col-md-8 fs-4">Find the latest bikes, parts, accessories, and more.</p>
            <button class="btn btn-dark btn-lg" type="button"><a class="text-light" href="{% url 'listings:all_listings' %}">Explore </a></button>
        </div>
    </div>

    <div class="row align-items-md-stretch">
        <div class="col-md-6">
            <div class="h-100 p-5 text-white bg-dark rounded-3">
                <h2>Sell and Buy Faster</h2>
                <p>Find people nearby, connect, strike a deal, get paid, done.</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="h-100 p-5 text-white bg-dark border rounded-3">
                <h2>Unlimited Listings</h2>
                <p>Create an account and start listing immediately. No limits! No fees!</p>
            </div>
        </div>
    </div>

    <footer class="pt-3 mt-4 text-muted border-top">
        © BikeFinder 2021
    </footer>

  </div>
</main>

{%endblock content%} 

listings/templates/listings/index.html
{% extends "listings/base.html" %}

{%block content%}

<h3>Bike Find3r</h3>

<p>This is a homepage</p>

{%endblock content%}

listings/templates/listings/my_listings.html
{% extends "listings/base.html" %}
        
{% block content %}
                          
<h2 class="text-center mb-3">MY LISTINGS:</h2>
        
<div class="row">
	<div class="col">
		<div class="container text-center p-3">
			<table class="table text-center">
				<tr>
					<th>Product</th>
					<th>Date Listed</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
				{% for my_listing in my_listings %}
				<tr>
					<td>{{ my_listing.title }}</td>
					<td>{{ my_listing.list_date }}</td>
					<td><a class="btn btn-warning"  href="{% url 'listings:detail' my_listing.id %}">View</a></td>
					<td><a class="btn btn-warning"  href="{% url 'listings:edit_listing' my_listing.id %}">Edit</a></td>
					<td><a class="btn btn-warning"  href="{% url 'listings:delete_listing' my_listing.id %}">Delete</a></td>
				</tr>
				{% endfor %}
      		</table>
      		<div class="container text-center">
      			<a class="btn btn-warning"  href="{% url 'listings:new_listing'%}">New Listing</a>
        	</div>
    	</div>
    </div>
</div>     
        
{% endblock content %}

listings/templates/listings/new_listing.html
{% extends "listings/base.html" %}
{% load crispy_forms_tags %}
        
{%block content%} 
<h2 class="p-3 text-center">NEW LISTING</h2>
<div class="container" style="width: 50%;">
    <form action="{% url 'listings:new_listing' %}" method='post' enctype="multipart/form-data">
    {% csrf_token %}
            
    <div class="row">
        <div class="col">{{ form.title|as_crispy_field }}</div>
        <div class="col">{{ form.product_type|as_crispy_field }}</div>
    </div>
            
    <div class="row">
        <div class="col">{{ form.condition|as_crispy_field }}</div>
        <div class="col">{{ form.sale_type|as_crispy_field }}</div>
    </div>
        
    <div class="row">
        <div class="col">{{ form.city|as_crispy_field }}</div>
        <div class="col">{{ form.state|as_crispy_field }}</div>
        <div class="col">{{ form.zipcode|as_crispy_field }}</div>
    </div>
        
    <div class="row">
        <div class="col">{{ form.price|as_crispy_field }}</div>
        <div class="col">{{ form.contact_email|as_crispy_field }}</div>
    </div>
        
    <div class="row">
        <div class="col-6">{{ form.main_photo|as_crispy_field }}</div>
        <div class="col-6">{{ form.photo_1|as_crispy_field }}</div>
    </div>
        
    <div class="row">
        <div class="col-6">{{ form.photo_2|as_crispy_field }}</div>
    </div>

    <div class="row">
        <div class="col-6">{{ form.list_date|as_crispy_field }}</div>
    </div>
              
    <div class = "container text-center p-3">
        <button type="submit" class="btn btn-warning">Create Listing</button>
    </div>
    </form>
</div>
                      
{%endblock content%} 